WITH 
    RANKING_SALARIES AS 
    (SELECT ID, SALARY, DENSE_RANK()OVER(ORDER BY SALARY DESC) AS RANKING
    FROM EMPLOYEE)

SELECT MIN(SALARY) AS SecondHighestSalary
FROM RANKING_SALARIES
WHERE RANKING = 2