WITH CTE AS (
    SELECT D.NAME AS Department, E.NAME AS Employee, E.SALARY AS Salary, RANK() OVER(PARTITION BY E.DEPARTMENTID ORDER BY E.SALARY DESC) AS RNK
    FROM EMPLOYEE E
    JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
)

SELECT
    Department,
    Employee,
    Salary
FROM CTE
WHERE RNK = 1