WITH EMP1 AS (
    SELECT EMPLOYEE_ID, DEPARTMENT_ID
    FROM EMPLOYEE
    GROUP BY EMPLOYEE_ID
    HAVING COUNT(DEPARTMENT_ID) = 1
), EMP2 AS (
    SELECT EMPLOYEE_ID, DEPARTMENT_ID
    FROM EMPLOYEE
    WHERE PRIMARY_FLAG = 'Y'
)

SELECT * FROM EMP1
UNION
SELECT * FROM EMP2
ORDER BY EMPLOYEE_ID;