/*
Count of damage types by year, 2013–2026
*/
SELECT 
    DT.YEAR, 
    F.DAMAGE, 
    COUNT(F.CRASH_RECORD_ID) AS DAMAGE_MONEY
FROM FACT_CRASH F
JOIN DIM_TIME DT ON DT.TIME_ID = F.TIME_ID AND DT.YEAR <= CAST(STRFTIME('%Y', CURRENT_DATE) AS INTEGER)
GROUP BY DT.YEAR, F.DAMAGE

/*
1. For each level of damage, what is the average number of uninjured people and fatal injuries?
*/

WITH TABLE_WITH_SUBGROUPS AS (
    SELECT 
        CRASH_RECORD_ID,
        INJURIES_FATAL,
        INJURIES_NO_INDICATION,
        -- Creamos el subgrupo en este paso intermedio
        CASE 
            WHEN DAMAGE = 'OVER $1,500' THEN 'HIGH IMPACT'
            ELSE 'LOW/MED IMPACT'
        END AS SUBGROUP_IMPACT
    FROM FACT_CRASH
)

SELECT 
    SUBGROUP_IMPACT,
    COUNT(CRASH_RECORD_ID) AS TOTAL_CRASHES,
    AVG(COALESCE(INJURIES_NO_INDICATION, 0)) AS AVG_NO_INDICATION,
    AVG(COALESCE(INJURIES_FATAL, 0)) AS AVG_FATAL
FROM TABLE_WITH_SUBGROUPS
GROUP BY SUBGROUP_IMPACT;

/*
2. What are the 3 primary causes that result in the highest number of total casualties when the driver fails to yield the right of way?
*/

SELECT 
    DCT.PRIM_CONTRIBUTORY_CAUSE, 
    SUM(COALESCE(F.INJURIES_TOTAL, 0)) AS TOTAL_INJURIES
FROM FACT_CRASH F
JOIN DIM_CAUSES_TYPES DCT ON F.CAUSES_TYPES_ID = DCT.CAUSES_TYPES_ID
JOIN DIM_ROAD_CRTCS DRC ON F.ROAD_CRTCS_ID = DRC.ROAD_CRTCS_ID
WHERE DRC.NOT_RIGHT_OF_WAY_I = 1
GROUP BY DCT.PRIM_CONTRIBUTORY_CAUSE
ORDER BY TOTAL_INJURIES DESC
LIMIT 3

