/*
Accident count by street and the time slot with the highest number of occurrences.
*/

WITH AUX AS (
    SELECT 
        DL.FULL_STREET_NAME,
        DL.TYPE_STREET AS STREET_TYPE,
        CASE
            WHEN F.CRASH_HOUR BETWEEN 0 AND 5 THEN 'EARLY_MORNING'
            WHEN F.CRASH_HOUR BETWEEN 6 AND 11 THEN 'MORNING'
            WHEN F.CRASH_HOUR BETWEEN 12 AND 19 THEN 'AFTERNOON'
            ELSE 'NIGHT'
        END AS TIME_SLOT,
        COUNT(F.CRASH_RECORD_ID) AS TOTAL_CRASHES
    FROM FACT_CRASH F
    JOIN DIM_TIME DT ON F.TIME_ID = DT.TIME_ID
    JOIN DIM_LOCATION DL ON F.LOCATION_ID = DL.LOCATION_ID
    GROUP BY DL.FULL_STREET_NAME, DL.TYPE_STREET, TIME_SLOT
),
RANKED_CRASHES AS (
    SELECT 
        FULL_STREET_NAME, 
        STREET_TYPE,
        TIME_SLOT, 
        TOTAL_CRASHES,
        ROW_NUMBER() OVER(PARTITION BY FULL_STREET_NAME ORDER BY TOTAL_CRASHES DESC) AS CRASH_RNK
    FROM AUX
)

SELECT 
    FULL_STREET_NAME,
    STREET_TYPE,
    TIME_SLOT,
    TOTAL_CRASHES
FROM RANKED_CRASHES
WHERE CRASH_RNK = 1
ORDER BY TOTAL_CRASHES DESC

/*
Analysis of Year-over-Year Trends in Road Accidents by Street and Weather Conditions
*/

WITH METRICS_WEATHER AS (
    SELECT 
        DT.YEAR, 
        DL.FULL_STREET_NAME AS STREET,
        SUM(CASE WHEN DAC.WEATHER_CONDITION = 'CLEAR' THEN 1 ELSE 0 END) AS CRASHES_CLEAR_WEATHER,
        SUM(CASE WHEN DAC.WEATHER_CONDITION = 'SNOW' THEN 1 ELSE 0 END) AS CRASHES_SNOW_WEATHER,
        SUM(CASE WHEN DAC.WEATHER_CONDITION = 'RAIN' THEN 1 ELSE 0 END) AS CRASHES_RAIN_WEATHER,
        SUM(CASE WHEN DAC.WEATHER_CONDITION NOT IN ('CLEAR', 'SNOW', 'RAIN') THEN 1 ELSE 0 END) AS CRASHES_OTHER_WEATHER,
        COUNT(F.CRASH_RECORD_ID) AS NUM_CRASHES
    FROM FACT_CRASH F
    JOIN DIM_AMB_CND DAC ON F.AMB_CND_ID = DAC.AMB_CND_ID
    JOIN DIM_LOCATION DL ON F.LOCATION_ID = DL.LOCATION_ID
    JOIN DIM_TIME DT ON F.TIME_ID = DT.TIME_ID
    GROUP BY DL.FULL_STREET_NAME, DT.YEAR
    HAVING DT.YEAR >= 2024
),
METRICS_LAGGED AS (
    SELECT 
        YEAR, 
        STREET,
        ROUND(CRASHES_CLEAR_WEATHER * 100.0 / NUM_CRASHES, 2) AS PCT_CLEAR,
        ROUND(CRASHES_SNOW_WEATHER * 100.0 / NUM_CRASHES, 2) AS PCT_SNOW,
        ROUND(CRASHES_RAIN_WEATHER * 100.0 / NUM_CRASHES, 2) AS PCT_RAIN,
        ROUND(CRASHES_OTHER_WEATHER * 100.0 / NUM_CRASHES, 2) AS PCT_OTHER,
        NUM_CRASHES,
        LAG(NUM_CRASHES, 1, 0) OVER(PARTITION BY STREET ORDER BY YEAR) AS PREVIOUS_NUM_CRASHES
    FROM METRICS_WEATHER
)
SELECT 
    YEAR,
    STREET,
    PCT_CLEAR,
    PCT_SNOW,
    PCT_RAIN,
    PCT_OTHER,
    NUM_CRASHES,
    PREVIOUS_NUM_CRASHES,
    CASE
        WHEN PREVIOUS_NUM_CRASHES = 0 THEN 'N/A' 
        ELSE CAST(ROUND(((NUM_CRASHES - PREVIOUS_NUM_CRASHES) * 100.0 / PREVIOUS_NUM_CRASHES), 2) AS TEXT) || '%' 
    END AS CRASHES_EVOLUTION
FROM METRICS_LAGGED
ORDER BY STREET, YEAR


/*
1. Which are the 5 streets with the highest number of accidents involving serious injuries in areas where the speed limit is low (< 30 mph)? 
This identifies stretches where drivers do not observe the limit.
*/

SELECT 
    DL.FULL_STREET_NAME,
	SUM(CASE WHEN (COALESCE(F.INJURIES_FATAL, 0) > 0 OR COALESCE(F.INJURIES_INCAPACITATING, 0) > 0) THEN 1 ELSE 0 END) AS SEVERE_INJURY_CRASHES
FROM FACT_CRASH F
JOIN DIM_LOCATION DL ON F.LOCATION_ID = DL.LOCATION_ID
WHERE F.POSTED_SPEED_LIMIT < 30
GROUP BY DL.FULL_STREET_NAME
ORDER BY SEVERE_INJURY_CRASHES DESC
LIMIT 5

/*
2. When there is roadwork, what is the most common type of crash compared to regular streets? Do rear-end collisions increase?
*/

WITH CRASHES_BY_WORK_ZONE_STATUS AS( 
    SELECT DCT.FIRST_CRASH_TYPE, 
        SUM(CASE WHEN F.WORK_ZONE_I = 1 THEN 1 ELSE 0 END) AS WORK_ZONE_CRASHES,
        SUM(CASE WHEN COALESCE(F.WORK_ZONE_I, 0) = 0 THEN 1 ELSE 0 END) AS NON_WORK_ZONE_CRASHES
    FROM FACT_CRASH F
    JOIN DIM_CAUSES_TYPES DCT ON F.CAUSES_TYPES_ID = DCT.CAUSES_TYPES_ID
    GROUP BY DCT.FIRST_CRASH_TYPE
)

SELECT
    FIRST_CRASH_TYPE,
    ROUND(WORK_ZONE_CRASHES * 100.0 / SUM(WORK_ZONE_CRASHES) OVER(), 2) AS PCT_WORK_ZONE,
    ROUND(NON_WORK_ZONE_CRASHES * 100.0 / SUM(NON_WORK_ZONE_CRASHES) OVER(), 2) AS PCT_NON_WORK_ZONE
FROM CRASHES_BY_WORK_ZONE_STATUS
ORDER BY PCT_WORK_ZONE DESC

/*
3.1. What percentage of fatal accidents occur at intersections versus standard road segments?
*/

SELECT 
    CASE
        WHEN COALESCE(DRC.INTERSECTION_RELATED_I, 0) = 1 THEN 'INTERSECTION'
        ELSE 'NON_INTERSECTION'
    END AS TYPE,
    SUM(CASE WHEN F.INJURIES_FATAL > 0 THEN 1 ELSE 0 END) AS DEADLY_CRASHES,
    ROUND(
        SUM(CASE WHEN F.INJURIES_FATAL > 0 THEN 1 ELSE 0 END) * 100.0 /
        SUM(SUM(CASE WHEN F.INJURIES_FATAL > 0 THEN 1 ELSE 0 END)) OVER(), 
        2
    ) AS PCT_GLOBAL
FROM FACT_CRASH F
JOIN DIM_ROAD_CRTCS DRC ON F.ROAD_CRTCS_ID = DRC.ROAD_CRTCS_ID
GROUP BY COALESCE(DRC.INTERSECTION_RELATED_I, 0)

/*
3.2. Does this percentage change depending on the street design (`TRAFFICWAY_TYPE`)?
*/

WITH AUX AS (
    SELECT
        DRC.TRAFFICWAY_TYPE AS WAY_TYPE,
        DRC.INTERSECTION_RELATED_I AS INTERSECTION,
        SUM(CASE WHEN INJURIES_FATAL > 0 THEN 1 ELSE 0 END) AS DEADLY_CRASHES
    FROM FACT_CRASH F
    JOIN DIM_ROAD_CRTCS AS DRC ON F.ROAD_CRTCS_ID = DRC.ROAD_CRTCS_ID
    GROUP BY DRC.TRAFFICWAY_TYPE, DRC.INTERSECTION_RELATED_I
)
    
SELECT
    WAY_TYPE,
    CASE WHEN INTERSECTION = 1 THEN 'INTERSECTION' ELSE 'NON_INTERSECTION' END AS TYPE,
    ROUND(DEADLY_CRASHES * 100.0/ SUM(DEADLY_CRASHES)OVER(PARTITION BY WAY_TYPE), 2) AS PCT_DEADLY_CRASHES
FROM AUX