/*
1. How do adverse weather conditions (such as rain or snow) combined with poor road surface conditions 
affect the total number of units involved in a single crash?
*/

SELECT 
    CASE 
        WHEN DAC.WEATHER_CONDITION IN ('RAIN','SNOW') 
            AND DRC.ROADWAY_SURFACE_COND IN ('ICE', 'SNOW OR SLUSH', 'SAND, MUD, DIRT', 'WET') 
            THEN 'BAD_CONDITIONS'
        WHEN DAC.WEATHER_CONDITION = 'CLEAR' 
            AND DRC.ROADWAY_SURFACE_COND = 'DRY' 
            THEN 'GOOD_CONDITIONS'
        ELSE 'OTHER_CONDITIONS'
    END AS CONDITIONS,
    COUNT(F.CRASH_RECORD_ID) AS TOTAL_CRASHES, 
    SUM(F.NUM_UNITS) AS TOTAL_UNITS, 
    ROUND((SUM(F.NUM_UNITS) * 1.0/COUNT(F.CRASH_RECORD_ID)), 2) AS UNITS_PER_CRASH
FROM FACT_CRASH F
JOIN DIM_AMB_CND DAC ON F.AMB_CND_ID = DAC.amb_cnd_id
JOIN DIM_ROAD_CRTCS DRC ON F.ROAD_CRTCS_ID = DRC.ROAD_CRTCS_ID
GROUP BY CONDITIONS

/*
2. Under conditions of total darkness, do non-functioning traffic lights or STOP signs multiply the hit-and-run accident rate?
*/

SELECT
	CASE 
        WHEN DAC.LIGHTING_CONDITION LIKE '%DARK%' 
             AND DRC.DEVICE_CONDITION IN ('FUNCTIONING IMPROPERLY')
             THEN 'DARKNESS W/ BAD DEVICE CONDITIONS'
        WHEN DAC.LIGHTING_CONDITION LIKE '%DARK%' 
             AND DRC.DEVICE_CONDITION = 'FUNCTIONING PROPERLY'
             THEN 'DARKNESS W/ GOOD DEVICE CONDITIONS'
        WHEN DAC.LIGHTING_CONDITION = 'DAYLIGHT' 
             THEN 'DAYLIGHT'
        ELSE 'OTHER CONDITIONS'
    END AS CONDITIONS,
	COUNT(F.CRASH_RECORD_ID) AS TOTAL_CRASHES,
	SUM(CASE WHEN UPPER(DCT.HIT_AND_RUN_I) = 'Y' THEN 1 ELSE 0 END) AS TOTAL_HNR,
	ROUND(SUM(CASE
			WHEN DCT.HIT_AND_RUN_I IN ('N', 'UNKNOWN') THEN 0 ELSE 1 END) * 100.0 
	/ COUNT(F.CRASH_RECORD_ID), 2) AS PCT_HNR
	
FROM FACT_CRASH F
JOIN DIM_AMB_CND DAC ON F.AMB_CND_ID = DAC.AMB_CND_ID
JOIN DIM_ROAD_CRTCS DRC ON F.ROAD_CRTCS_ID = DRC.road_crtcs_id
JOIN DIM_CAUSES_TYPES DCT ON F.CAUSES_TYPES_ID = DCT.CAUSES_TYPES_ID
GROUP BY CONDITIONS
HAVING CONDITIONS != 'OTHER CONDITIONS'
ORDER BY PCT_HNR

/*
Rainfall Impact Analysis: Streets Exceeding Average Wet-Weather Crash Rates.
*/

WITH PCT_CRASHES_RAIN AS (
    SELECT
        DL.FULL_STREET_NAME AS STREET,
        COUNT(F.CRASH_RECORD_ID) AS NUM_CRASHES,
        ROUND(
            SUM(CASE WHEN DAC.WEATHER_CONDITION = 'RAIN' THEN 1 ELSE 0 END) * 100.0 / COUNT(F.CRASH_RECORD_ID), 
            2
        ) AS PCT_RAIN
    FROM FACT_CRASH F
    JOIN DIM_LOCATION DL ON F.LOCATION_ID = DL.LOCATION_ID
    JOIN DIM_AMB_CND DAC ON F.AMB_CND_ID = DAC.AMB_CND_ID
    GROUP BY DL.FULL_STREET_NAME
)
SELECT 
    STREET,
    NUM_CRASHES,
    PCT_RAIN
FROM PCT_CRASHES_RAIN
WHERE PCT_RAIN > (SELECT AVG(PCT_RAIN) FROM PCT_CRASHES_RAIN)
  AND NUM_CRASHES > 30
ORDER BY PCT_RAIN DESC;